### ISSUE TITLE
求问：能否出一个教程简易说明一下流程

### ISSUE THREAD

**Issue by Panic123OK** [depaler/RedmiBook-14-II-AMD-hackintosh#2]
我的型号是同cpu的红米16, 现在我参考了nootedred的教程，dump出了acpi的aml文件，整合你这边的efi, 偶尔可以进入到mac os 安装界面，但是触控板和键盘无效，另外会在 usbtoolbox处卡住，提示 xhci, 但是如果我关闭xhci的话，u盘就无法识别，也就进不去oc, 附EFI文件夹结构图，求大佬解疑, nootedred的教程到acpi之后就只有kexts, 后续的教程没了，实在找不到解决办法
![image](https://github.com/depaler/RedmiBook-14-II-AMD-hackintosh/assets/36023311/d8e9b189-f0ad-456e-8680-9ffbae55b078)
![image](https://github.com/depaler/RedmiBook-14-II-AMD-hackintosh/assets/36023311/57a240db-ba54-4002-a5d8-95a4c97e6d0c)

**Comment by Panic123OK** [comment]
下面是kexts
文件夹 PATH 列表
卷序列号为 F69E-1D1F
E:.
│  tree.txt
│  
├─AMDRyzenCPUPowerManagement.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─_CodeSignature
│      │      CodeResources
│      │      
│      └─MacOS
│              AMDRyzenCPUPowerManagement
│              
├─AmdTscSync.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              AmdTscSync
│              
├─AppleALC.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              AppleALC
│              
├─AppleMCEReporterDisabler.kext
│  └─Contents
│          Info.plist
│          
├─BrightnessKeys.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              BrightnessKeys
│              
├─ECEnabler.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              ECEnabler
│              
├─FeatureUnlock.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              FeatureUnlock
│              
├─HoRNDIS.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─MacOS
│      │      HoRNDIS
│      │      
│      └─Resources
│          └─en.lproj
│                  InfoPlist.strings
│                  
├─Lilu.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              Lilu
│              
├─NootedRed.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              NootedRed
│              
├─NullEthernet.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              NullEthernet
│              
├─NVMeFix.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              NVMeFix
│              
├─RadeonSensor.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              RadeonSensor
│              
├─RestrictEvents.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              RestrictEvents
│              
├─RTCMemoryFixup.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              RTCMemoryFixup
│              
├─RtWlanDisk.kext
│  └─Contents
│      │  CodeResources
│      │  Info.plist
│      │  
│      ├─_CodeSignature
│      │      CodeResources
│      │      
│      └─MacOS
│              RtWlanDisk
│              
├─RtWlanU.kext
│  └─Contents
│      │  CodeResources
│      │  Info.plist
│      │  
│      ├─_CodeSignature
│      │      CodeResources
│      │      
│      └─MacOS
│              RtWlanU
│              
├─RtWlanU1827.kext
│  └─Contents
│      │  CodeResources
│      │  Info.plist
│      │  
│      ├─_CodeSignature
│      │      CodeResources
│      │      
│      └─MacOS
│              RtWlanU1827
│              
├─SMCAMDProcessor.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─_CodeSignature
│      │      CodeResources
│      │      
│      └─MacOS
│              SMCAMDProcessor
│              
├─SMCBatteryManager.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─MacOS
│      │      SMCBatteryManager
│      │      
│      └─Resources
│              SSDT-BATC.dsl
│              
├─SMCLightSensor.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              SMCLightSensor
│              
├─SMCRadeonGPU.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              SMCRadeonGPU
│              
├─USBToolBox.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              USBToolBox
│              
├─UTBMap.kext
│  └─Contents
│          Info.plist
│          
├─VirtualSMC.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              VirtualSMC
│              
├─VoodooI2CFTE.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              VoodooI2CFTE
│              
├─ApplePS2SmartTouchPad.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─MacOS
│      │      ApplePS2SmartTouchPad
│      │      
│      ├─PlugIns
│      │  ├─ApplePS2Controller.kext
│      │  │  └─Contents
│      │  │      │  Info.plist
│      │  │      │  
│      │  │      └─MacOS
│      │  │              ApplePS2Controller
│      │  │              
│      │  └─ApplePS2Keyboard.kext
│      │      └─Contents
│      │          │  Info.plist
│      │          │  
│      │          └─MacOS
│      │                  ApplePS2Keyboard
│      │                  
│      └─Resources
│          ├─Features Documentation.rtfd
│          │      11493706554_130fa58d5f_n.jpg
│          │      8524384148_7da070dae6_c.jpg
│          │      9718452526_b6414cd8e7_n.jpg
│          │      TXT.rtf
│          │      
│          └─Synaptics documentation.rtfd
│                  page30image13008.png
│                  page30image13432.png
│                  page30image13912.png
│                  page30image14840.png
│                  page30image15160.png
│                  page30image16448.png
│                  page30image16608.png
│                  page30image18496.png
│                  page30image18808.png
│                  page30image20328.png
│                  page30image21840.png
│                  page30image22000.png
│                  page30image24168.png
│                  page30image24328.png
│                  page30image25088.png
│                  page30image25248.png
│                  page30image26496.png
│                  page30image26984.png
│                  page30image28496.png
│                  page30image29088.png
│                  page30image31456.png
│                  page30image31616.png
│                  page30image31776.png
│                  page30image31936.png
│                  page30image32096.png
│                  page30image32256.png
│                  page30image32416.png
│                  page30image33264.png
│                  page30image33848.png
│                  page30image34168.png
│                  page30image34328.png
│                  page30image34920.png
│                  page30image35080.png
│                  page30image35672.png
│                  page30image35992.png
│                  page30image36312.png
│                  page30image36472.png
│                  page30image36632.png
│                  page30image36792.png
│                  page30image36952.png
│                  page30image37112.png
│                  page30image37272.png
│                  page30image38680.png
│                  page30image39000.png
│                  page30image40360.png
│                  page30image41264.png
│                  page30image42512.png
│                  page30image42992.png
│                  page30image44072.png
│                  page30image44392.png
│                  page30image45080.png
│                  page30image45400.png
│                  page30image45872.png
│                  page30image47224.png
│                  page30image47840.png
│                  page30image48000.png
│                  page30image49832.png
│                  page30image49992.png
│                  page30image50744.png
│                  page30image51992.png
│                  page30image52480.png
│                  page30image53728.png
│                  page30image54320.png
│                  page30image54640.png
│                  page30image56688.png
│                  page30image56848.png
│                  page30image57008.png
│                  page30image57328.png
│                  page30image57488.png
│                  page30image57648.png
│                  page30image58464.png
│                  page30image59048.png
│                  page30image59368.png
│                  page30image59528.png
│                  page30image60112.png
│                  page30image60272.png
│                  page30image60432.png
│                  page30image61880.png
│                  page30image62040.png
│                  page30image62200.png
│                  page30image63104.png
│                  page30image63424.png
│                  page30image63744.png
│                  page30image64064.png
│                  page30image64672.png
│                  page30image64832.png
│                  page30image65424.png
│                  page30image65744.png
│                  page30image65904.png
│                  page30image66064.png
│                  page30image66224.png
│                  page30image67312.png
│                  page30image67472.png
│                  page30image67632.png
│                  page30image68112.png
│                  page30image68432.png
│                  page30image68856.png
│                  page30image69176.png
│                  page42image103272.png
│                  page42image105384.png
│                  page42image105808.png
│                  page42image75600.png
│                  page42image75760.png
│                  page42image76080.png
│                  page42image76672.png
│                  page42image76832.png
│                  page42image77440.png
│                  page42image77600.png
│                  page42image77920.png
│                  page42image78240.png
│                  page42image78848.png
│                  page42image79272.png
│                  page42image81272.png
│                  page42image82192.png
│                  page42image83992.png
│                  page42image84520.png
│                  page42image85104.png
│                  page42image85528.png
│                  page42image86456.png
│                  page42image86936.png
│                  page42image87360.png
│                  page42image88112.png
│                  page42image88272.png
│                  page42image88912.png
│                  page42image93040.png
│                  page42image95864.png
│                  page42image96184.png
│                  page42image97536.png
│                  page42image99496.png
│                  page43image24304.png
│                  page43image24464.png
│                  page43image24784.png
│                  page43image25376.png
│                  page43image25536.png
│                  page43image26144.png
│                  page43image26304.png
│                  page43image26624.png
│                  page43image26944.png
│                  page43image27568.png
│                  page43image28152.png
│                  page43image29984.png
│                  page43image30408.png
│                  page43image30736.png
│                  page43image31160.png
│                  page43image32696.png
│                  page43image33232.png
│                  page43image33392.png
│                  page43image33816.png
│                  page43image34240.png
│                  page43image35168.png
│                  page43image35648.png
│                  page43image35968.png
│                  page43image36720.png
│                  page43image36880.png
│                  page43image37520.png
│                  page43image46136.png
│                  page43image48136.png
│                  page43image48560.png
│                  page43image49048.png
│                  page43image50440.png
│                  page43image51704.png
│                  page43image52024.png
│                  page43image53736.png
│                  page43image54056.png
│                  page43image54544.png
│                  page43image55936.png
│                  TXT.rtf
│                  
├─VoodooI2C.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─MacOS
│      │      VoodooI2C
│      │      
│      └─PlugIns
│          ├─VoodooGPIO.kext
│          │  └─Contents
│          │      │  Info.plist
│          │      │  
│          │      └─MacOS
│          │              VoodooGPIO
│          │              
│          ├─VoodooI2CServices.kext
│          │  └─Contents
│          │      │  Info.plist
│          │      │  
│          │      └─MacOS
│          │              VoodooI2CServices
│          │              
│          └─VoodooInput.kext
│              └─Contents
│                  │  Info.plist
│                  │  
│                  ├─MacOS
│                  │      VoodooInput
│                  │      
│                  └─_CodeSignature
│                          CodeResources
│                          
├─VoodooI2CHID.kext
│  └─Contents
│      │  Info.plist
│      │  
│      └─MacOS
│              VoodooI2CHID
│              
├─XHCI-Injector.kext
│  └─Contents
│          Info.plist
│          
├─VoodooPS2Controller.kext
│  └─Contents
│      │  Info.plist
│      │  
│      ├─MacOS
│      │      VoodooPS2Controller
│      │      
│      └─PlugIns
│          ├─VoodooInput.kext
│          │  └─Contents
│          │      │  Info.plist
│          │      │  
│          │      ├─MacOS
│          │      │      VoodooInput
│          │      │      
│          │      └─_CodeSignature
│          │              CodeResources
│          │              
│          ├─VoodooPS2Keyboard.kext
│          │  └─Contents
│          │      │  Info.plist
│          │      │  
│          │      └─MacOS
│          │              VoodooPS2Keyboard
│          │              
│          ├─VoodooPS2Mouse.kext
│          │  └─Contents
│          │      │  Info.plist
│          │      │  
│          │      └─MacOS
│          │              VoodooPS2Mouse
│          │              
│          └─VoodooPS2Trackpad.kext
│              └─Contents
│                  │  Info.plist
│                  │  
│                  └─MacOS
│                          VoodooPS2Trackpad
│                          
└─dSYM
    ├─VoodooInput.kext.dSYM
    │  └─Contents
    │      │  Info.plist
    │      │  
    │      └─Resources
    │          └─DWARF
    │                  VoodooInput
    │                  
    ├─VoodooPS2Controller.kext.dSYM
    │  └─Contents
    │      │  Info.plist
    │      │  
    │      └─Resources
    │          └─DWARF
    │                  VoodooPS2Controller
    │                  
    ├─VoodooPS2Keyboard.kext.dSYM
    │  └─Contents
    │      │  Info.plist
    │      │  
    │      └─Resources
    │          └─DWARF
    │                  VoodooPS2Keyboard
    │                  
    ├─VoodooPS2Mouse.kext.dSYM
    │  └─Contents
    │      │  Info.plist
    │      │  
    │      └─Resources
    │          └─DWARF
    │                  VoodooPS2Mouse
    │                  
    └─VoodooPS2Trackpad.kext.dSYM
        └─Contents
            │  Info.plist
            │  
            └─Resources
                └─DWARF
                        VoodooPS2Trackpad

**Comment by depaler** [comment]
你好，针对你的issues提出的问题，我可以提供给你几个可以尝试一下的方案。
1.本项目中有USBToolBox和UTBMap.kext这两个相似的kext，可以试试去掉USBToolBox？
2.触控板和键盘无效 ①试试在安装拔下u盘接入鼠标(拔u盘不会有事)，检测是否为系统卡死
                                     ②尝试新版voodoo系列驱动
3.教程的话可以参考 OpenCore官方手册 或者 https://dortania.github.io/OpenCore-Install-Guide/
b站上也有AMD核显的教程视频

**Comment by Panic123OK** [comment]
好的谢谢，已经准备放弃了，实在是不清楚具体什么情况，现在基本就卡死在acpi controller 初始化成功，然后power state changed, 没后续了，之前还能进安装界面，虽然语言不是中文也不是英文, 现在已经进不了了，也不确定是卡死还是什么。
